cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('detail/', views.cart_detail, name='cart_detail'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 11)]

class CartForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from products.models import Product
from .cart import Cart
from .forms import CartForm


@api_view(['POST'])
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, pk=product_id)
    form = CartForm(request.POST)
    if form.is_valid():
        is_detail = request.POST.get('is_detail', None)
        cd_quantity = form.cleaned_data['quantity']
        cd_update = form.cleaned_data['update']
        cart.add(product=product, quantity=cd_quantity, update=cd_update)
        if request.is_ajax():
            return Response(status=status.HTTP_201_CREATED)
        if is_detail is not None:
            return redirect(product)
        return redirect('cart:cart_detail')

@api_view(['GET'])
def cart_remove(request, product_id):
    cart = Cart(request)
    cart.remove(product_id)
    if request.is_ajax():
        data = {
            'get_total_price': cart.get_total_price(),
            'total_count': len(cart),
        }
        return Response(data=data)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    for product in cart:
        product['update_quantity_form'] = CartForm(initial={'quantity': product['quantity'], 'update': True})
    return render(request, 'cart/cart.html')

cart/templates/cart/cart.html
{% extends 'base.html' %}
{% load humanize %}
{% load imagekit %}

{% block content %}

<!-- Start Bradcaump area -->
<div class="ht__bradcaump__area bg-image--3">
	<div class="container">
		<div class="row">
			<div class="col-lg-12">
				<div class="bradcaump__inner text-center">
					<h2 class="bradcaump-title">Shopping Cart</h2>
					<nav class="bradcaump-content">
						<a class="breadcrumb_item" href="index.html">Home</a>
						<span class="brd-separetor">/</span>
						<span class="breadcrumb_item active">Shopping Cart</span>
					</nav>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Bradcaump area -->

<!-- cart-main-area start -->
<div class="cart-main-area section-padding--lg bg--white">
	<div class="container">
		<div class="row">
			<div class="col-md-12 col-sm-12 ol-lg-12">
				<form action="#">
					<div class="table-content wnro__table table-responsive">
						<table>
							<thead>
								<tr class="title-top">
									<th class="product-thumbnail">상품 이미지</th>
									<th class="product-name">상품</th>
									<th class="product-price">가격</th>
									<th class="product-quantity">수량</th>
									<th class="product-subtotal">소계</th>
									<th class="product-remove">삭제</th>
								</tr>
							</thead>
							<tbody>
								{% for item in cart %}
								<tr>
									{% thumbnail "150x150" item.product.get_image.image as thumb %}
									<td class="product-thumbnail"><a href="#"><img src="{{ thumb.url }}" alt="product img"></a></td>
									<td class="product-name"><a href="{{ item.product.get_absolute_url }}">{{ item.product.name }}</a></td>
									<td class="product-price"><span class="amount">{{ item.price | intcomma }}원</span></td>
									<td class="product-quantity">
										<form action=""></form>
										<form action="{% url 'cart:cart_add' item.product.id %}" method="POST">
											{% csrf_token %}
											{% for field in item.update_quantity_form.hidden_fields %}
												{{ field }}
											{% endfor %}
											<select name="{{ item.update_quantity_form.quantity.name }}" id="{{ item.update_quantity_form.quantity.id_for_label }}">
												{% for option in item.update_quantity_form.quantity %}
													{{ option }}
												{% endfor %}
											</select>
											<button class="btn btn-link btn-sm" style="color: black;">변경</button>
										</form>
									</td>
									<td class="product-subtotal">{{ item.total_price | intcomma }}원</td>
									<td class="product-remove"><a href="{% url 'cart:cart_remove' item.product.id %}">삭제</a></td>
								</tr>
								{% empty %}
									<h1>장바구니에 담긴 상품이 없습니다 ):</h1>
								{% endfor %}
							</tbody>
						</table>
					</div>
				</form>
				<div class="cartbox__btn">
					<ul class="cart__btn__list d-flex flex-wrap flex-md-nowrap flex-lg-nowrap justify-content-between">
						<li><a href="#">Coupon Code</a></li>
						<li><a href="#">Apply Code</a></li>
						<li><a href="#">Update Cart</a></li>
						<li><a href="#">Check Out</a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="row">
			<div class="col-lg-6 offset-lg-6">
				<div class="cartbox__total__area">
					<div class="cartbox-total d-flex justify-content-between">
						<!-- <ul class="cart__total__list">
							<li>Cart total</li>
							<li>Sub Total</li>
						</ul> -->
						<!-- <ul class="cart__total__tk">
							<li>$70</li>
							<li>$70</li>
						</ul> -->
					</div>
					<div class="cart__total__amount">
						<span>총 주문금액</span>
						<span>{{ cart.get_total_price | intcomma }}원</span>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- cart-main-area end -->

{% endblock content %}