cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('detail/', views.cart_detail, name='cart_detail'),
]

jinmaymall/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import redirect
from django.contrib import admin
from django.urls import path, include
from accounts import views as accounts_views
from products import views as products_views

def index(request):
    return redirect('products:product_list')

urlpatterns = [
    path('', index, name='root'),
    path('summernote/', include('django_summernote.urls')),

    path('admin/', admin.site.urls),

    path('accounts/', include('accounts.urls')),
    path('signup/', accounts_views.signup, name='signup'),
    path('login/', accounts_views.login, name='login'),
    path('logout/', accounts_views.logout, name='logout'),
    path('mypage/', accounts_views.mypage, name='mypage'),
    path('wishlist/', products_views.like_list, name='wishlist'),

    path('products/', include('products.urls')),
    path('cart/', include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jinmaymall/templates/_popup_cart.html
{% load humanize %}

<div class="block-minicart minicart__active">
  <div class="minicart-content-wrapper">
    <div class="micart__close">
      <span>close</span>
    </div>
    <div class="items-total d-flex justify-content-between">
      <span>총 수량 : <span id="total_count">{{ cart | length | intcomma }}</span>개</span>
      <span>총 주문금액</span>
    </div>
    <div class="total_amount text-right">
      <span><span id="total_price">{{ cart.get_total_price | intcomma }}</span>원</span>
    </div>
    <div class="mini_action checkout">
      <a class="checkout__btn" href="cart.html">결제하기</a>
    </div>
    <div class="single__items">
      <div class="miniproduct">
        {% for item in cart %}
        <div class="item01 d-flex mb-3" id="product-{{ item.product.id }}">
          <div class="thumb">
            <a href=""><img src="{{ item.product.get_image.image.url }}" alt="product images"></a>
          </div>
          <div class="content">
            <h6><a href="{{ item.product.get_absolute_url }}">{{ item.product.name }}</a></h6>
            <span class="prize">{{ item.total_price | intcomma }}원</span>
            <div class="product_prize d-flex justify-content-between">
              <span class="qun">수량: {{ item.quantity }}</span>
              <ul class="d-flex justify-content-end">
                <!-- <li><a href="#"><i class="zmdi zmdi-settings"></i></a></li> -->
                <li><a href="" class="remove-btn" data-target-rm="{{ item.product.id }}"><i class="zmdi zmdi-delete"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
    <div class="mini_action cart">
      <a class="cart__btn" href="{% url 'cart:cart_detail' %}">장바구니</a>
    </div>
  </div>
</div>

jinmaymall/templates/base.html
{% load static %}
{% load humanize %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">

  <!-- Google font (font-family: 'Roboto', sans-serif; Poppins ; Satisfy) -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Poppins:300,300i,400,400i,500,600,600i,700,700i,800"
    rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900" rel="stylesheet">

  <!-- Stylesheets -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/plugins.css' %}">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <!-- custom css -->
  <link rel="stylesheet" href="{% static 'css/custom.css' %}">

  {% block extra_css %}
  {% endblock extra_css %}

  <title>Document</title>
</head>

<body>

  <!-- Header -->
  <header id="wn__header" class="oth-page header__area header__absolute sticky__header">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-4 col-sm-4 col-7 col-lg-2">
          <div class="logo">
            <a href="{% url 'root' %}">
              <img src="images/logo/logo.png" alt="logo images">
            </a>
          </div>
        </div>
        <div class="col-lg-8 d-none d-lg-block">
          <nav class="mainmenu__nav">
            <ul class="meninmenu d-flex justify-content-start">
              <li class="drop with--one--item"><a href="{% url 'products:product_list' %}">Home</a></li>
              <!-- <li class="drop"><a href="#">Shop</a>
                <div class="megamenu mega03">
                  <ul class="item item03">
                    <li class="title">Shop Layout</li>
                    <li><a href="shop-grid.html">Shop Grid</a></li>
                    <li><a href="single-product.html">Single Product</a></li>
                  </ul>
                  <ul class="item item03">
                    <li class="title">Shop Page</li>
                    <li><a href="my-account.html">My Account</a></li>
                    <li><a href="cart.html">Cart Page</a></li>
                    <li><a href="checkout.html">Checkout Page</a></li>
                    <li><a href="wishlist.html">Wishlist Page</a></li>
                    <li><a href="error404.html">404 Page</a></li>
                    <li><a href="faq.html">Faq Page</a></li>
                  </ul>
                  <ul class="item item03">
                    <li class="title">Bargain Books</li>
                    <li><a href="shop-grid.html">Bargain Bestsellers</a></li>
                    <li><a href="shop-grid.html">Activity Kits</a></li>
                    <li><a href="shop-grid.html">B&N Classics</a></li>
                    <li><a href="shop-grid.html">Books Under $5</a></li>
                    <li><a href="shop-grid.html">Bargain Books</a></li>
                  </ul>
                </div>
              </li> -->
              <!-- <li><a href="contact.html">Contact</a></li> -->
              <li>
                <form class="form-inline" action="" method="GET">
                  <div class="input-group col">
                    <input type="text" class="form-control" placeholder="반품비 배송비 걱정없는 jinmaymall" size="50" name="q" value="{{ q }}">
                    <div class="input-group-append">
                      <button type="submit" class="btn btn-outline-secondary">
                        <i class="fa fa-search fa-1x" aria-hidden="true"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </li>
            </ul>
          </nav>
        </div>
        <div class="col-md-6 col-sm-6 col-6 col-lg-2">
          <ul class="header__sidebar__right d-flex justify-content-end align-items-center">
            {% if request.user.is_authenticated %}
            <li class="mr-3" style="color: white;">반갑습니다,<br>{{ request.user.username }} 고객님</li>
            {% endif %}

            {% if request.user.is_authenticated %}
            <!-- 위시리스트 시작 -->
            <li class="wishlist"><a href="{% url 'wishlist' %}"></a></li>
            <!-- 위시리스트 끝 -->
            {% endif %}

            <!-- 장바구니 시작 -->
            <li class="shopcart">
              <a class="cartbox_active" href="#">
                <span class="product_qun">{{ cart | length }}</span>
              </a>
              <!-- 팝업 장바구니 시작 -->
              {% include '_popup_cart.html' %}
              <!-- 팝업 장바구니 끝 -->
            </li>
            <!-- 장바구니 끝 -->

            <!-- 개인 설정 시작 -->
            <li class="setting__bar__icon"><a class="setting__active" href="#"></a>
              <div class="searchbar__content setting__block">
                <div class="content-inner">
                  <div class="switcher-currency">
                    <strong class="label switcher-label">
                      <span>My Account</span>
                    </strong>
                    <div class="switcher-options">
                      <div class="switcher-currency-trigger">
                        <div class="setting__menu">
                          <span><a href="{% url 'mypage' %}">My Account</a></span>
                          <span><a href="{% url 'cart:cart_detail' %}">My Cart</a></span>
                          {% if user.is_authenticated %}
                          <span><a href="{% url 'logout' %}?next={{ request.path }}">Log out</a></span>
                          {% else %}
                          <span><a href="{% url 'login' %}?next={{ request.path }}">Log In</a></span>
                          <span><a href="{% url 'signup' %}">Create An Account</a></span>
                          {% endif %}
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </li>
            <!-- 개인 설정 끝 -->
          </ul>
        </div>
      </div>
  </header>
  <!-- //Header -->

  {% block content %}
  {% endblock content %}

  <!-- Footer Area -->
  <footer id="wn__footer" class="footer__area bg__cat--8 brown--color">
    <div class="footer-static-top">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="footer__widget footer__menu">
              <div class="ft__logo">
                <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered
                  duskam alteration variations of passages</p>
              </div>
              <div class="footer__content">
                <ul class="social__net social__net--2 d-flex justify-content-center">
                  <!-- <li><a href="#"><i class="bi bi-facebook"></i></a></li>
                  <li><a href="#"><i class="bi bi-google"></i></a></li>
                  <li><a href="#"><i class="bi bi-twitter"></i></a></li>
                  <li><a href="#"><i class="bi bi-linkedin"></i></a></li>
                  <li><a href="#"><i class="bi bi-youtube"></i></a></li> -->
                </ul>
                <ul class="mainmenu d-flex justify-content-center">
                  <li><a href="{% url 'products:product_list' %}">All Product</a></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="copyright__wrapper">
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-12">
            <div class="copyright">
              <div class="copy__right__inner text-left">
                <p>Copyright <i class="fa fa-copyright"></i> <a href="https://freethemescloud.com/">Free themes
                    Cloud.</a> All Rights Reserved</p>
              </div>
            </div>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-12">
          </div>
        </div>
      </div>
    </div>
  </footer>
  <!-- //Footer Area -->

  <!-- Modernizer js -->
  <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>

  <!-- JS Files -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/plugins.js' %}"></script>
  <script src="{% static 'js/active.js' %}"></script>
  <script src="{% static 'products/js/ajax.js' %}"></script>
  <script>
    // js에서 intcomma를 해주기 위한 함수입니다
    function numberWithCommas(x) {
        return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
      }

    $('.remove-btn').click(function (e) {
      e.preventDefault();
      let product_id = e.currentTarget.dataset.targetRm;
      let url = "{% url 'cart:cart_remove' 0 %}".replace("0", product_id);
      let targetData = $("#product-" + product_id);

      $.get({
        url: url,
        data: {
          product_id: product_id
        },
        success: function (res) {
          targetData.remove();
          $('#total_count').html(res.total_count);
          $('#total_price').html(numberWithCommas(res.get_total_price));
          $('.product_qun').html(res.total_count)
        }
      });
    });
  </script>
  {% block extra_js %}
  {% endblock extra_js %}
</body>

</html>