cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('add/<int:product_id>', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>', views.cart_remove, name='cart_remove'),
    path('detail/', views.cart_detail, name='cart_detail'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<int:product_id>/', views.product_detail, name='product_detail'),
    path('<int:product_id>/likes/', views.toggle_like, name='toggle_like'),
    path('<int:product_id>/review/', views.review, name='review'),
    path('<int:product_id>/review/<int:review_id>/', views.review_edit, name='review_edit'),
    path('<int:product_id>/review/<int:review_id>/delete/', views.review_delete, name='review_delete'),
    path('answer/<int:qna_id>/', views.answer, name='answer'),
]

products/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.urls import reverse
from django.contrib.auth import get_user_model

User = get_user_model()


class Category(models.Model):
    name = models.CharField(max_length=50)

    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    @property
    def product_count(self):
        return self.product_set.filter(is_active=True).count()

class ProductManager(models.Manager):
    def filter_by_category(self, category_id):
        if category_id:
            qs = Product.objects.filter(category_id=category_id, is_active=True)
        else:
            qs = Product.objects.filter(is_active=True)
        return qs

class ProductImage(models.Model):
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='images')
    image = models.ImageField()
    is_representative = models.BooleanField()

class Product(models.Model):
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    name = models.CharField(max_length=128)
    price = models.IntegerField()
    short_desc = models.TextField()
    long_desc = models.TextField()
    is_active = models.BooleanField(default=True)
    hit = models.IntegerField(default=0)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    objects = ProductManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('products:product_detail', kwargs={'product_id': self.id})

    @property
    def like_count(self):
        return self.like.count()

    @property
    def get_image(self):
        image = ProductImage.objects.get(product=self, is_representative=True)
        return image 

    def get_like(self, user):
        try:
            like = Like.objects.get(user=user, product=self)
        except Like.DoesNotExist:
            like = None
        return like

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return "{} - {}".format(self.user, self.product)


class Post(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    is_finished = models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('-id', )

    def __str__(self):
        return self.title


class Answer(models.Model):
    qna = models.OneToOneField(Post, on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}의 답변".format(self.qna_id)


class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    content = models.TextField()
    rating = models.PositiveSmallIntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{} 상품의 리뷰".format(self.product)

products/forms.py
from django import forms
from .models import Post, Answer, Review

class ProductImageInlineFormset(forms.models.BaseInlineFormSet):

    def clean(self):
        count = 0
        for form in self.forms:
            try:
                if form.cleaned_data['is_representative']:
                    count += 1
            except:
                pass
        if count > 1:
            raise forms.ValidationError('대표 사진이 두 장 이상입니다. 하나의 사진만 대표 사진으로 지정해주세요.')
        if count == 0:
            raise forms.ValidationError('대표 사진이 없습니다. 하나의 사진으르 대표사진으로 지정해주세요.')
            

class QnaForm(forms.ModelForm):
    
    class Meta:
        model = Post
        fields = ('title', 'content', )


class AnswerForm(forms.ModelForm):

    class Meta:
        model = Answer
        fields = ('content', )

    
class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('title', 'content', 'rating', )
        

class ReviewEditForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ('content', )

products/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import AnonymousUser
from django.contrib.auth import get_user_model
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from cart.forms import CartForm
from .models import Category, Product, Like, Post, Review
from .forms import QnaForm, AnswerForm, ReviewForm, ReviewEditForm


UserModel = get_user_model()


class ProductListView(ListView):
    model = Product
    template_name = 'products/product_list.html'
    paginate_by = 15

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all()
        context['product_total_count'] = Product.objects.filter(is_active=True).count()
        context['q'] = self.request.GET.get('q', "")
        context['qq'] = self.request.GET.get('qq', "")
        context['category_id'] = self.request.GET.get('category', None)
        return context

    def get_queryset(self):
        q = self.request.GET.get('q', None)
        qq = self.request.GET.get('qq', None)
        category_id = self.request.GET.get('category', None)
        qs = Product.objects.filter_by_category(category_id)
        if q:
            qs = qs.filter(name__icontains=q)
        elif qq:
            qs = qs.filter(name__icontains=qq, category_id=category_id)
        return qs

product_list = ProductListView.as_view()


def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    category_list = Category.objects.all()
    product_total_count = Product.objects.count()
    qna_list = Post.objects.filter(product=product)
    cart_form = CartForm()
    qnaform = QnaForm()
    review_form = ReviewForm()
    try:
        like = product.get_like(request.user)
    except:
        like = None

    if request.user.is_staff:
        answer_form = AnswerForm()
    else:
        answer_form = None

    if request.method == 'POST':
        form = QnaForm(request.POST)
        if form.is_valid():
            qna = form.save(commit=False)
            qna.author = request.user
            qna.product =product
            qna.save()
            return redirect(product)

    return render(request, 'products/product_detail.html', {
        'cart_form': cart_form,
        'product': product,
        'category_list': category_list,
        'product_total_count': product_total_count,
        'like': like,
        'qnaform': qnaform,
        'qna_list': qna_list,
        'answer_form': answer_form,
        'review_form': review_form,
    })

# 유저 객체가 AnonymousUser클래스의 인스턴스인지 확인 후
# AnonymousUser의 객체 -> 로그인 페이지로 redirect
# 로그인한 유저 객체 -> 비동기로 좋아요 기능을 수행
@api_view(['POST'])
def toggle_like(request, product_id):
    user = request.user
    if isinstance(user, AnonymousUser):
        data = {
            'is_login': False
        }
        return Response(data=data, status=status.HTTP_200_OK)

    product = get_object_or_404(Product, pk=product_id)
    data = {
        'is_login': True,
        'is_existed': None
    }
    try:
        product_like = Like.objects.get(user=user, product=product)
        product_like.delete()
        data['is_existed'] = False
    except Like.DoesNotExist:
        Like.objects.create(user=user, product=product)
        data['is_existed'] = True
    
    return Response(data=data, status=status.HTTP_200_OK)


# 위시리스트
def like_list(request):
    return render(request, 'products/wishlist.html')

# QnA의 답변을 생성하는 함수입니다
def answer(request, qna_id):
    qna = get_object_or_404(Post, pk=qna_id)
    product = qna.product
    if request.method == 'POST':
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.qna = qna
            answer.save()
            return redirect(product)

# 새로운 리뷰 생성에 사용할 함수입니다
def review(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    user = request.user

    # 이미 작성한 리뷰가 있으면 리뷰를 생성하는 로직을 거치지 않고
    # 현재의 상품으로 리다이렉트 합니다
    review = Review.objects.filter(product=product, user=user)
    if review:
        return redirect(product)

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.product = product
            review.user = user
            review.save()
            return redirect(product)
        return redirect(product)

# 리뷰 게시글 수정에 사용할 함수입니다
def review_edit(request, product_id, review_id):
    user = request.user
    product = get_object_or_404(Product, pk=product_id)
    review = get_object_or_404(Review, pk=review_id)

    if request.method == 'POST':
        form = ReviewEditForm(request.POST, instance=review)
        print(form)
        if form.is_valid():
            print('valid')
            edited_review = form.save(commit=False)
            edited_review.title = review.title
            edited_review.product = product
            edited_review.user = user
            edited_review.rating = review.rating
            edited_review.save()
            return redirect(product)
        print('invalid')
        return redirect(product)

# 리뷰 게시글 삭제 함수
@api_view(['GET'])
def review_delete(request, product_id, review_id):
    if request.is_ajax():
        review = get_object_or_404(Review, pk=review_id, product_id=product_id, user=request.user)
        review.delete()
        return Response(status=status.HTTP_204_NO_CONTENT)

products/templates/products/_answer_modal.html
<!-- Modal -->
<div class="modal fade" id="answer-{{ post.id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">QnA 게시판 답변하기</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <form action="{% url 'products:answer' post.id %}" method="POST">
          {% csrf_token %}
          <textarea name="{{ answer_form.content.name }}" cols="70" rows="5"></textarea>
          <div class="modal-footer">
            <input type="submit" class="btn btn-secondary" data-dismiss="modal" value="닫기">
            <input type="submit" class="btn btn-primary" value="등록하기">
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- End Single Tab Content -->

products/templates/products/_banner.html
<aside class="wedget__categories sidebar--banner">
  <img src="images/others/banner_left.jpg" alt="banner images">
  <div class="text">
    <h2>new products</h2>
    <h6>save up to <br> <strong>40%</strong>off</h6>
  </div>
</aside>

products/templates/products/_category.html
<aside class="wedget__categories poroduct--cat">
  <h3 class="wedget__title">카테고리</h3>
  <ul>
    <li><a href="{% url 'products:product_list' %}">전체<span>({{ product_total_count }})</span></a></li>
    {% for category in category_list %}
    <li><a href="{% url 'products:product_list' %}?category={{ category.id }}">{{ category.name }}
        <span>({{ category.product_count }})</span></a></li>
    {% endfor %}
  </ul>
</aside>

products/templates/products/_compare.html
<aside class="wedget__categories poroduct--compare">
  <h3 class="wedget__title">Compare</h3>
  <ul>
    <li><a href="#">x</a><a href="#">Condimentum posuere</a></li>
  </ul>
</aside>

products/templates/products/_nav_detail.html
<!-- Start Single Tab Content -->
<div class="pro__tab_label tab-pane fade show active" id="nav-details" role="tabpanel">
  <div class="description__attribute">
    <p>
      {{ product.long_desc }}
    </p>
  </div>
</div>
<!-- End Single Tab Content -->

products/templates/products/_nav_review.html
<!-- Start Single Tab Content -->
<div class="pro__tab_label tab-pane fade" id="nav-review" role="tabpanel">
  <!-- <div class="review__attribute">
    <div class="review__ratings__type d-flex">
      <div class="review-ratings">
        <div class="rating-summary d-flex">
          <span>Quality</span>
          <ul class="rating d-flex">
            <li><i class="zmdi zmdi-star"></i></li>
            <li><i class="zmdi zmdi-star"></i></li>
            <li><i class="zmdi zmdi-star"></i></li>
            <li class="off"><i class="zmdi zmdi-star"></i></li>
            <li class="off"><i class="zmdi zmdi-star"></i></li>
          </ul>
        </div>

        <div class="rating-summary d-flex">
          <span>Price</span>
          <ul class="rating d-flex">
            <li><i class="zmdi zmdi-star"></i></li>
            <li><i class="zmdi zmdi-star"></i></li>
            <li><i class="zmdi zmdi-star"></i></li>
            <li class="off"><i class="zmdi zmdi-star"></i></li>
            <li class="off"><i class="zmdi zmdi-star"></i></li>
          </ul>
        </div>
        <div class="rating-summary d-flex">
          <span>value</span>
          <ul class="rating d-flex">
            <li><i class="zmdi zmdi-star"></i></li>
            <li><i class="zmdi zmdi-star"></i></li>
            <li><i class="zmdi zmdi-star"></i></li>
            <li class="off"><i class="zmdi zmdi-star"></i></li>
            <li class="off"><i class="zmdi zmdi-star"></i></li>
          </ul>
        </div>
      </div>
      <div class="review-content">
        <p>Hastech</p>
        <p>Review by Hastech</p>
        <p>Posted on 11/6/2018</p>
      </div>
    </div>
  </div> -->
  
  <div id="accordion" class="wn_accordion" role="tablist">
    {% for review in product.review_set.all %}
    <div class="card">
      <div class="acc-header" role="tab" id="headingOne">
        <h5>
          <a data-toggle="collapse" href="#collapse-{{ review.id }}" role="button" aria-expanded="false"
            aria-controls="collapseOne" class="collapsed">
            {{ review.title }}
            {% if request.user.username == review.user.username %}
            <button type="button" class="btn btn-outline-info btn-sm" data-toggle="modal" data-target="#review-{{ review.id }}-modal">
              수정하기
            </button>
            <button type="button" class="btn btn-outline-danger btn-sm" onclick="review_delete('{{ product.id }}', '{{ review.id }}');">
              삭제하기
            </button>
            {% endif %}
            <input type="hidden" id="review-{{ review.id }}" value="{{ review.rating }}">
            <span class="pull-right">{{ review.user.username }}</span>
          </a>
        </h5>
      </div>
      <div id="collapse-{{ review.id }}" class="collapse" role="tabpanel" aria-labelledby="headingOne"
        data-parent="#accordion">
        <div class="starrr" id="review-{{ review.id }}" style="padding-left: 17px;"></div>
        <span class="card-text pull-right pr-2">{{ review.updated }}</span>
        <div class="card-body">{{ review.content }}</div>
      </div>
    </div>
    {% include 'products/_edit_review.html' %}
    {% endfor %}
  </div>
  
  <div class="review-fieldset">    
    <h3>후기를 남겨 주세요</h3>
    <form action="{% url 'products:review' product.id %}" method="POST">
      {% csrf_token %}
      <div class="review_form_field">
        <div class="input__box">
          <span>제목</span>
          <input id="{{ review_form.title.id_for_label }}" type="{{ review_form.title.field.widget.input_type }}" name="{{ review_form.title.name }}">
        </div>
        <div class="input__box">
          <span>만족도</span>
          <div id="input_starrr" class="starrr"></div>
          <input type="hidden" id="{{ review_form.rating.id_for_label }}" value="3" name="{{ review_form.rating.name }}">
        </div>
        <div class="input__box">
          <span>내용</span>
          <textarea name="{{ review_form.content.name }}"></textarea>
        </div>
        <div class="review-form-actions" data-id="{{ product.id }}">
          <button>후기 남기기</button>
        </div>
      </div>
    </form>
  </div>
</div>
<!-- End Single Tab Content -->

products/templates/products/_tag.html
<aside class="wedget__categories poroduct--tag">
  <h3 class="wedget__title">Product Tags</h3>
  <ul>
    <li><a href="#">Biography</a></li>
  </ul>
</aside>

products/templates/products/product_detail.html
{% extends 'products/base.html' %}

{% load static %}
{% load humanize %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'products/css/starrr.css' %}">
{% endblock extra_css %}

{% block content %}

<!-- Start Bradcaump area -->
<div class="ht__bradcaump__area bg-image--4">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="bradcaump__inner text-center">
          <h2 class="bradcaump-title">Shop Single</h2>
          <nav class="bradcaump-content">
            <a class="breadcrumb_item" href="index.html">Home</a>
            <span class="brd-separetor">/</span>
            <span class="breadcrumb_item active">Shop Single</span>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- End Bradcaump area -->

<div class="maincontent bg--white pt--80 pb--55">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-12">
        <div class="wn__single__product">
          <div class="row">
            <div class="col-lg-6 col-12">
              <div class="wn__fotorama__wrapper">
                <div class="fotorama wn__fotorama__action" data-nav="thumbs">
                  {% for image in product.images.all %}
                  <a href=""><img src="{{ image.image.url }}" alt=""></a>
                  {% endfor %}
                </div>
              </div>
            </div>
            <div class="col-lg-6 col-12">
              <div class="product__info__main">
                <h1>{{ product.name }}</h1>
                <!-- <div class="product-reviews-summary d-flex">
                  <ul class="rating-summary d-flex">
                    <li><i class="zmdi zmdi-star-outline"></i></li>
                    <li><i class="zmdi zmdi-star-outline"></i></li>
                    <li><i class="zmdi zmdi-star-outline"></i></li>
                    <li class="off"><i class="zmdi zmdi-star-outline"></i></li>
                    <li class="off"><i class="zmdi zmdi-star-outline"></i></li>
                  </ul>
                </div> -->
                <div class="price-box">
                  <span>{{ product.price | intcomma }}원</span>
                </div>
                <div class="product__overview">
                  {{ product.short_desc }}
                </div>
                
                <div class="box-tocart d-flex">
                  <form action="{% url 'cart:cart_add' product.id %}" method="POST" class="d-flex">
                    {% csrf_token %}
                    {% for field in cart_form.hidden_fields %}
                      {{ field }}
                    {% endfor %}
                    <span for="{{ cart_form.quantity.id_for_label }}">수량</span>
                    <select id="{{ cart_form.quantity.id_for_label }}" class="input-text qty" name="{{ cart_form.quantity.name }}">
                      {% for option in cart_form.quantity %}
                      {{ option }}
                      {% endfor %}
                    </select>
                    <div class="addtocart__actions">
                      <input type="hidden" name="is_detail" value="True">
                      <button id="cart_btn" class="tocart" type="submit" title="Add to Cart">장바구니에 추가</button>
                    </div>
                  </form>
                  <div class="product-addto-links clearfix">
                    <a class="wishlist like" href="{% url 'products:toggle_like' product.id %}" value="{{ product.id }}"
                      {% if like %}style="background-color: #e59285; background-position: 100% center;" {% endif %}></a>
                    <!-- <a class="compare" href="#"></a> -->
                  </div>
                </div>

                <div class="product_meta">
                  <span class="posted_in">카테고리 -
                    <a href="{% url 'products:product_list' %}?category={{ product.category.id }}">{{ product.category }}</a>
                  </span>
                </div>
                <!-- <div class="product-share">
                  <ul>
                    <li class="categories-title">Share :</li>
                    <li>
                      <a href="#">
                        <i class="icon-social-twitter icons"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="icon-social-tumblr icons"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="icon-social-facebook icons"></i>
                      </a>
                    </li>
                    <li>
                      <a href="#">
                        <i class="icon-social-linkedin icons"></i>
                      </a>
                    </li>
                  </ul>
                </div> -->
              </div>
            </div>
          </div>
        </div>
        <div class="product__info__detailed">
          <div class="pro_details_nav nav justify-content-start" role="tablist">
            <a class="nav-item nav-link active" data-toggle="tab" href="#nav-details" role="tab">Details</a>
            <a class="nav-item nav-link" data-toggle="tab" href="#nav-review" role="tab">Reviews</a>
            <a class="nav-item nav-link" data-toggle="tab" href="#nav-qna" role="tab">QnA</a>
          </div>
          <div class="tab__container">
            {% include 'products/_nav_detail.html' %}
            {% include 'products/_nav_review.html' %}
            {% include 'products/_nav_qna.html' %}
          </div>
        </div>
      </div>
      <div class="col-lg-3 col-12 md-mt-40 sm-mt-40">
        <div class="shop__sidebar">
          {% include 'products/_category.html' %}
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

{% block extra_js %}
<script src="{% static 'products/js/ajax.js' %}"></script>
<script src="{% static 'products/js/starrr.js' %}"></script>
<script>
  $(".like").click(function (e) {
    e.preventDefault();
    let product_id = $(this).attr("value");
    let url = "{% url 'products:toggle_like' 0 %}".replace("0", product_id);
    $.ajax({
      type: "POST",
      url: url,
      data: {
        product_id: product_id
      },
      success: function (res) {
        let is_existed = res.is_existed;
        let is_login = res.is_login;

        // 로그인하지 않은 유저의 요청일 경우 js로 리다이렉트를 해줍니다
        if (!is_login) {
          window.location.href = "{% url 'login' %}";
        }

        if (is_existed) {
          $(".like").css("background-color", "#e59285");
          $(".like").css("background-position-x", "100%");
          $(".like").css("background-position-y", "center");
        } else {
          $(".like").css("background", "");
          $(".like").css("background-position-x", "");
          $(".like").css("background-position-y", "");
        }
      },
      error: function (request, status, error) {
        console.log(error);
      }
    });
  });
</script>
<script>
  $('#cart_btn').click(function(e) {
    alert('장바구니에 추가되었습니다')
  });
</script>
<script>
  let rating_input = $('#id_rating');
  $('#input_starrr').starrr({
    rating: rating_input.val(),
    change: function(e, value) {
      rating_input.val(value).trigger('input');
    }
  })
</script>
{% for review in product.review_set.all %}
<script>
  $('#review-{{ review.id }}.starrr').starrr({
    rating: "{{ review.rating }}"
  })
</script>
{% endfor %}
<script>
// _nav_review.html 파일에서 사용
// 리뷰를 삭제하기 위한 함수입니다
function review_delete(product_id, review_id) {
  let approval = confirm('정말 후기를 삭제하시겠습니까?')
  if (approval) {
    let url = "{% url 'products:review_delete' 0 1 %}".replace("0", product_id).replace("1", review_id);
    $.get({
      url: url,
    }).done(function () {
      location.reload();
    })
  } else {
    location.reload();
  }
}
</script>
{% endblock extra_js %}

products/templates/products/wishlist.html
{% extends 'products/base.html' %}
{% load static %}
{% load humanize %}
{% load imagekit %}

{% block content %}
<html class="no-js" lang="zxx">

<body>
  <!-- Main wrapper -->
  <div class="wrapper" id="wrapper">

    <!-- Start Bradcaump area -->
    <div class="ht__bradcaump__area bg-image--5">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="bradcaump__inner text-center">
              <h2 class="bradcaump-title">Wishlist</h2>
              <nav class="bradcaump-content">
                <a class="breadcrumb_item" href="index.html">Home</a>
                <span class="brd-separetor">/</span>
                <span class="breadcrumb_item active">Wishlist</span>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- End Bradcaump area -->

    <!-- cart-main-area start -->
    <div class="wishlist-area section-padding--lg bg__white">
      <div class="container">
        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="wishlist-content">
              <form action="#">
                <div class="wishlist-table wnro__table table-responsive">
                  <table>
                    <thead>
                      {% if user.like_set.all %}
                      <tr>
                        <th class="product-remove"></th>
                        <th class="product-thumbnail text-center">사진</th>
                        <th class="product-name"><span class="nobr">상품</span></th>
                        <th class="product-price"><span class="nobr">가격</span></th>
                        <!-- <th class="product-stock-stauts"><span class="nobr"> Stock Status </span></th> -->
                        <th class="product-add-to-cart"></th>
                      </tr>
                      {% endif %}
                    </thead>
                    <tbody>
                      {% for like in user.like_set.all %}
                      {% thumbnail "150x150" like.product.get_image.image as thumb %}
                      <tr id="remove-{{ like.product_id }}" data-id="{{ like.product_id }}">
                        <td class="product-remove remove-like"><a href="#">×</a></td>
                        <td class="product-thumbnail text-center"><a href="#"><img src="{{ thumb.url }}"
                              alt=""></a></td>
                        <td class="product-name"><a href="#">{{ like.product }}</a></td>
                        <td class="product-price"><span class="amount">{{ like.product.price | intcomma }}원</span></td>
                        <!-- <td class="product-stock-status"><span class="wishlist-in-stock">In Stock</span></td> -->
                        <td class="product-add-to-cart add-cart"><a href="#"> 장바구니 추가</a></td>
                      </tr>
                      {% empty %}
                        <h1>위시리스트에 담긴 상품이 없습니다 ):</h1>
                      {% endfor %}
                    </tbody>
                  </table>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- cart-main-area end -->

  </div>
  <!-- //Main wrapper -->
</body>

</html>
{% endblock content %}

{% block extra_js %}
<script src="{% static 'products/js/ajax.js' %}"></script>
<script>
  $('.remove-like').click(function (e) {
    e.preventDefault();
    let target_id = e.currentTarget.parentElement.dataset.id;
    let url = "{% url 'products:toggle_like' 0 %}".replace("0", target_id);
    let remove_tr = $("#remove-" + target_id)

    $.post({
      url: url,
      success: function (res) {
        remove_tr.remove();
      },
      error: function (request, status, err) {
        console.log(err);
      },
    })
  })

  $('.add-cart').click(function (e) {
    e.preventDefault();
    let target_id = e.currentTarget.parentElement.dataset.id;
    let url = "{% url 'cart:cart_add' 0 %}".replace("0", target_id);
    let remove_tr = $("#remove-" + target_id)
    let remove_url = "{% url 'products:toggle_like' 0 %}".replace("0", target_id);

    $.post({
      url: url,
      data: {
        quantity: 1
      },
      success: function(res) {
        alert('장바구니에 추가했습니다!')
        $.post({
          url: remove_url,
          success: function (res) {
            remove_tr.remove();
            location.reload();
          }
        })
      },
      error: function(err) {
        console.log(err);
      },
    })
  })
</script>
{% endblock extra_js %}